### ISSUE TITLE
Update the holopin.yaml to use the quickstarts badge

### ISSUE THREAD

**Issue by marcduiker** [dapr/quickstarts#1004]
Update the `.github/holopin.yaml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clrqfb88y222860gjxdlaobhpt) for this repo:

```yaml
organization: dapr
defaultSticker: clrqfb88y222860gjxdlaobhpt
stickers:
  -
    id: clrqfb88y222860gjxdlaobhpt
    alias: quickstarts-badge
```

Once this is in place, maintainers can award contributors via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`

---

Please label this as a __good first issue__.
