### ISSUE TITLE
Support for IRSA for AWS Components Specs

### ISSUE THREAD

**Issue by elamaran11** [dapr/quickstarts#1098]
## Describe the feature

Team -

I currently see that [component](https://docs.dapr.io/reference/components-reference/) specs with AWS integrations dont have support IRSA (IAM Roles for Service Account), rather we are expected to plug in the secret and access keys as part of the deployment for example like below and this basically increases the blast radius and also exposes keys to operator of the EKS Cluster. Appreciate if you can provide support for [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) with all AWS Components implementation.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.aws.dynamodb
  version: v1
  metadata:
    - name: table
      value: "Orders"
    - name: accessKey
      secretKeyRef:
        name: statestore-secrets
        key: accessKey
    - name: secretKey
      secretKeyRef:
        name: statestore-secrets
        key: secretKey
    - name: region
      secretKeyRef:
        name: statestore-secrets
        key: region
    - name: partitionKey
      value: "orderId"
```
