### ISSUE TITLE
5.bindings report JSON parse error with  bindings.azure.storagequeues

### ISSUE THREAD

**Issue by heavenwing** [dapr/quickstarts#269]
## Expected Behavior
I replaced bindings.kafka with bindings.azure.storagequeues.
There are no any errors in demo.
I think that dapr app should not depend on the implementation of bindings.

## Actual Behavior
It reports JSON parse error when received event.
Actually, it still reports some error after stopping publish event.
Error logs is below: 
![Annotation 2020-07-31 181205](https://user-images.githubusercontent.com/2920062/89025870-2c2ebf80-d35a-11ea-8801-124679491d57.png)

## Steps to Reproduce the Problem

1. deploy azure.storagequeues binding with this yaml file:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sample-topic
  namespace: default
spec:
  type: bindings.azure.storagequeues
  metadata:
    - name: storageAccount
      value: "youraccount"
    - name: storageAccessKey
      value: "***"
    - name: queue
      value: "daprevents"
    - name: ttlInSeconds
      value: "60"
```

2. deploy bindings-nodeapp via "kubectl apply -f .\node.yaml"

3. deploy bindings-pythonapp via "kubectl apply -f .\python.yaml"
