### ISSUE TITLE
dapr components does not connect with redis using double-quoted metadata

### ISSUE THREAD

**Issue by Johnsonxd4** [dapr/quickstarts#291]
## Expected Behavior
Running example distributed-calculator available on this quickstarts, i've noticed the `redis.yaml` located in the deployment folder does not work, the component do not connect with the redis instance. This happened because the `redis.yaml` available on this example is double quoted.

## Actual Behavior
Removing the double quotes, connects just fine, as the example as follows:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: "OUR_REDIS_HOST_HERE
  - name: redisPassword
    value: YOUR_REDIS_PASSWORD_HERE
```

## Steps to Reproduce the Problem

To reproduce this issue, just follow the actual documentation , and try to run the calculator.
