### ISSUE TITLE
how to expose DAPR_HTTP_PORT and DAPR_GRPC_PORT in hello-kubernetes when service type is NodePort

### ISSUE THREAD

**Issue by dybxin** [dapr/quickstarts#355]
## Ask your question here

how to expose DAPR_HTTP_PORT and DAPR_GRPC_PORT in hello-kubernetes when service type is NodePort.
in [hello-kubernetes](https://github.com/dapr/quickstarts/tree/master/hello-kubernetes) steps 3 and steps 4.

show: Once you have an external IP, save it. You can also export it to a variable:
```bash
Linux/MacOS
export NODE_APP=$(kubectl get svc nodeapp --output 'jsonpath={.status.loadBalancer.ingress[0].ip}')

Windows
for /f "delims=" %a in ('kubectl get svc nodeapp --output 'jsonpath={.status.loadBalancer.ingress[0].ip}') do @set NODE_APP=%a
```
but how to expose dapr_http_port and dapr_grpc_port in not  an external IP and service type is NodePort.

```yaml
kind: Service
apiVersion: v1
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: node
        image: dapriosamples/hello-k8s-node:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always

```
