### ISSUE TITLE
in pub-sub example: upstream connect error or disconnect/reset before headers. reset reason: connection failure

### ISSUE THREAD

**Issue by dybxin** [dapr/quickstarts#356]
## Ask your question here
i modify the react-form.yaml(modify kind: Service -->type:NodePort ):

```yaml
 kind: Service
apiVersion: v1
metadata:
  name: react-form
  labels:
    app: react-form
spec:
  selector:
    app: react-form
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30002
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-form
  labels:
    app: react-form
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-form
  template:
    metadata:
      labels:
        app: react-form
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "react-form"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: react-form
        image: dapriosamples/pubsub-react-form:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
```

when i deployed all services,  i use http://ip:30002/  to publish message, the publish get error:
 `upstream connect error or disconnect/reset before headers. reset reason: connection failure`
