### ISSUE TITLE
[Distributed-calculator] Got 400 error when I deployed to aks

### ISSUE THREAD

**Issue by sheng-jie** [dapr/quickstarts#365]
I deployed the demo to aks according to the document guidelines, and it prompts 400 when I visit the calculator website. The error is as follows.

![400 Error](https://user-images.githubusercontent.com/12607748/104534614-8fce5000-564f-11eb-8160-d75f193e2b23.png)

After analysis, check the daprd container log and find the error log:
```
2021-01-12T14:53:25.966648603Z time="2021-01-12T14:53:25.966545203Z" level=error msg="error getting secret: secrets \"redis\" is forbidden: User \"system:serviceaccount:dapr:default\" cannot get resource \"secrets\" in API group \"\" in the namespace \"dapr\"" app_id=multiplyapp instance=multiplyapp-56bcbdff6c-lm75n scope=dapr.runtime type=log ver=0.11.3
2021-01-12T14:53:25.969698819Z time="2021-01-12T14:53:25.969613018Z" level=warning msg="error initializing state store state.redis: redis store: error connecting to redis at redis-master:6379: NOAUTH Authentication required." app_id=multiplyapp instance=multiplyapp-56bcbdff6c-lm75n scope=dapr.runtime type=log ver=0.11.3
```

That's mean the default service account has no permission to the redis sceret (Which deploy by helm with bitnami/redis).

So I create a ClusterRoleBinding to solve the issue.
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: admin
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: dapr
```

The purpose of writing this issue is to help beginners so as not to get into trouble, so I suggest to update the document and give relevant tips. I have created a PR for that.
