### ISSUE TITLE
Tracing inside kubernetes cluster not working

### ISSUE THREAD

**Issue by RevathiNeminathan** [dapr/quickstarts#392]
## Ask your question here
I have initialized dapr inside kubernetes cluster(minikube) and tried to do tracing using zipkin with distributed calculator which is working fine but the same is not working with my dotnet application.

When I do post request, I get expected result from postman but there is no trace details in zipkin.

Please find yaml files below

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtract1app
  labels:
    app: subtract1app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtract1app
  template:
    metadata:
      labels:
        app: subtract1app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subtract1app"
        dapr.io/app-port: "7300"
        dapr.io/config: "daprconfig"
    spec:
      containers:
      - name: subtract1app
        image: testdapr2:latest
        ports:
        - containerPort: 7300
        imagePullPolicy: Never
```

Tracing daprconfig.yaml file
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
```

**DockerFile**
```
FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
WORKDIR /src
COPY ["Subtract.csproj", "./"]
RUN dotnet restore "Subtract.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "Subtract.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Subtract.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS http://*:7300
ENTRYPOINT ["dotnet", "Subtract.dll"]
```

**Dapr Version details:**
CLI version: 1.0.0 
Runtime version: 1.0.0

Can anyone help to resolve this issue?
