### ISSUE TITLE
NOAUTH Authentication required

### ISSUE THREAD

**Issue by wajika** [dapr/quickstarts#464]
```
time="2021-08-11T10:14:06.808069638Z" level=info msg="starting Dapr Runtime -- version 1.3.0 -- commit 4bab7576ed68a9ece1a4743a7925f18ef583775a" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.80810177Z" level=info msg="log level set to: info" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.808186022Z" level=info msg="metrics server started on :9090/" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.metrics type=log ver=1.3.0 
time="2021-08-11T10:14:06.808275585Z" level=info msg="loading default configuration" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.808310731Z" level=info msg="kubernetes mode configured" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.80831907Z" level=info msg="app id: subtractapp" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.808476563Z" level=info msg="mTLS enabled. creating sidecar authenticator" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.808607771Z" level=info msg="trust anchors and cert chain extracted successfully" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime.security type=log ver=1.3.0 
time="2021-08-11T10:14:06.808619528Z" level=info msg="authenticator created" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.816669789Z" level=info msg="Initialized name resolution to kubernetes" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.819071504Z" level=info msg="component loaded. name: kubernetes, type: secretstores.kubernetes/v1" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.835934506Z" level=error msg="error getting secret: secrets \"redis\" is forbidden: User \"system:serviceaccount:dapr-system:default\" cannot get resource \"secrets\" in API group \"\" in the namespace \"dapr-system\"" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.836915161Z" level=warning msg="error initializing state store statestore (state.redis/v1): redis store: error connecting to redis at redis-master:6379: NOAUTH Authentication required." app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.836940181Z" level=warning msg="process component error daprd process will exited, gracefully to stop" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:06.836955577Z" level=info msg="dapr shutting down. Waiting 5s to finish outstanding operations" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:11.837695761Z" level=info msg="Shutting down all components" app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
time="2021-08-11T10:14:11.837733628Z" level=fatal msg="process component statestore error: redis store: error connecting to redis at redis-master:6379: NOAUTH Authentication required." app_id=subtractapp instance=subtractapp-64fc749bd7-px5pr scope=dapr.runtime type=log ver=1.3.0 
```

I have created two files redis-pubsub.yaml and redis-state.yaml which have specified the password.

```
cat redis-pubsub.yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: dapr-system
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: "KD9wyqgCZG"
```

```
cat redis-state.yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: dapr-system
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: "KD9wyqgCZG"
```
