### ISSUE TITLE
Add Multi-App Run for Kubernetes to the Pub/Sub Tutorial

### ISSUE THREAD

**Issue by msfussell** [dapr/quickstarts#915]
Adding example for the Multi-App Run for Kubernetes in the v1.12 release to the Pub/Sub Tutorial
This one https://github.com/dapr/quickstarts/tree/master/tutorials/pub-sub

**Comment by mukundansundar** [comment]
A potential template to use for this: 
Present in tutorials/pub-sub/dapr.yaml

```yaml
version: 1
apps:
  - appDirPath: ./node-subscriber
    appPort: 3000
    command: ["node", "app.js"]
    containerImage: ghcr.io/dapr/samples/pubsub-node-subscriber:latest
  - appDirPath: ./python-subscriber
    appPort: 5001
    command: ["python3", "app.py"]
    containerImage: ghcr.io/dapr/samples/pubsub-python-subscriber:latest
  - appDirPath: ./csharp-subscriber
    appPort: 5009
    command: ["dotnet", "run", "csharp-subscriber.csproj"]
    containerImage: ghcr.io/dapr/samples/pubsub-csharp-subscriber:latest
  - appDirPath: ./react-form
    appPort: 8080
    command: ["npm", "run", "start"]
    containerImage: ghcr.io/dapr/samples/pubsub-react-form:latest
    createService: true
```
